foodplan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts.views import HomePageView, ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('order/', include('order.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile', ProfileView.as_view(), name='profile'),
    path('', HomePageView.as_view(), name='home')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from .views import create_order, success_payment

app_name = "order"

urlpatterns = [
    path('create/', create_order, name='create_order'),
    path('success_payment/', success_payment, name='success_payment'),
]

recipes/urls.py
from django.urls import path

from .views import create_recipe, get_recipe_by_id

app_name = "recipes"

urlpatterns = [
    path('api/create', create_recipe),
    path('<int:recipe_id>/', get_recipe_by_id, name='recipe_page'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.templatetags.static import static



class Profile(models.Model):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, ("Male")),
        (GENDER_FEMALE, ("Female")),
    ]

    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    avatar = models.ImageField(null=True, blank=True, default='test_avatar.png')
    birthday = models.DateField(null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    number = models.CharField(max_length=32, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    zip = models.CharField(max_length=30, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = ('Profile')
        verbose_name_plural = ('Profiles')

    @property
    def get_avatar(self):
        return self.avatar.url if self.avatar else static('test_avatar.png')

accounts/forms.py
from django import forms
from .models import Profile


class UserUpdateForm(forms.ModelForm):
    name = forms.CharField(label='На что влияет?', max_length=100)
    email = forms.CharField(label='Your имейл', max_length=100)

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user', 'email']

def form_validation_error(form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field, 'label') else 'Error', error)
    return msg

order/views.py
from django import forms
from django.conf import settings
from django.shortcuts import redirect
from django.shortcuts import render

from recipes.models import FoodCategory, AllergyCategory
from .models import Promocode, Order


class OrderForm(forms.Form):
    ONEMONTH = 1
    THREEMONTH = 3
    SIXMONTH = 6
    TWELVEMONTH = 12
    TIME_CHOICES = [
        (ONEMONTH, '1 месяц'),
        (THREEMONTH, '3 месяца'),
        (SIXMONTH, '6 месяцев'),
        (TWELVEMONTH, '12 месяцев'),
    ]
    TRUE_VALUE = 50
    FALSE_VALUE = 0
    BOOL_CHOICES = [
        (TRUE_VALUE, '✔'),
        (FALSE_VALUE, '✘'),
    ]
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5
    SIX = 6
    PERSON_AMOUNT = [
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5'),
        (SIX, '6'),
    ]
    time = forms.ChoiceField(choices=TIME_CHOICES,
                             widget=forms.Select(
                                 attrs={'class': 'form-select',
                                        'onchange': 'submit();'}))
    breakfast = forms.ChoiceField(choices=BOOL_CHOICES,
                                  widget=forms.Select(
                                      attrs={'class': 'form-select',
                                             'onchange': 'submit();'}))
    lunch = forms.ChoiceField(choices=BOOL_CHOICES,
                              widget=forms.Select(
                                  attrs={'class': 'form-select',
                                         'onchange': 'submit();'}))
    dinner = forms.ChoiceField(choices=BOOL_CHOICES,
                               widget=forms.Select(
                                   attrs={'class': 'form-select',
                                          'onchange': 'submit();'}))
    dessert = forms.ChoiceField(choices=BOOL_CHOICES,
                                widget=forms.Select(
                                    attrs={'class': 'form-select',
                                           'onchange': 'submit();'}))
    amount_person = forms.ChoiceField(choices=PERSON_AMOUNT,
                                      widget=forms.Select(
                                          attrs={'class': 'form-select',
                                                 'onchange': 'submit();'}))
    milk_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))
    nuts_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))
    honey_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))
    cereal_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))
    meat_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))
    fish_allergy = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input me-1 foodplan_checked-green',
                   'onchange': 'submit();'}))


class PromoForm(forms.Form):
    promocode = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control me-2'}))


class FoodCategoryForm(forms.Form):
    CLASSIC = 100
    LOWCARB = 200
    VEGETERIAN = 300
    KETO = 400
    FOOD_CHOICES = [
        (CLASSIC, 'Классическое'),
        (LOWCARB, 'Низкокалорийное'),
        (VEGETERIAN, 'Вегетарианское '),
        (KETO, 'Кето'),
    ]
    food_category = forms.ChoiceField(choices=FOOD_CHOICES,
                                      widget=forms.RadioSelect(
                                          attrs={'name': 'foodtype',
                                                 'class': 'foodplan_selected d-none',
                                                 'onchange': 'submit(); changeMilk(this);'}))


def create_order(request):
    if request.user.is_anonymous:
        return render(request, 'account/login.html')
    logged_user = request.user
    order, created = Order.objects.get_or_create(user=logged_user)
    if order.is_paid:
        return redirect('/profile')
    user_promocode = ""
    correct_promocode = False

    form = OrderForm(request.POST or None)
    promo_form = PromoForm(request.POST or None)
    food_form = FoodCategoryForm(request.POST or None)
    if food_form.is_valid():
        food_form_cost = int(food_form.cleaned_data.get("food_category"))
        if food_form_cost == 100:
            order.category = FoodCategory.objects.get(title='Классическое')
        if food_form_cost == 200:
            order.category = FoodCategory.objects.get(title='Низкокалорийное')
        if food_form_cost == 300:
            order.category = FoodCategory.objects.get(title='Вегетарианское')
        if food_form_cost == 400:
            order.category = FoodCategory.objects.get(title='Кето')
        order.food_form_cost = food_form_cost
        order.save()
    if form.is_valid():
        order.time = form.cleaned_data.get("time")
        breakfast = form.cleaned_data.get("breakfast")
        if breakfast == '0':
            order.breakfast = False
        else:
            order.breakfast = True
        lunch = form.cleaned_data.get("lunch")
        if lunch == '0':
            order.lunch = False
        else:
            order.lunch = True
        dinner = form.cleaned_data.get("dinner")
        if dinner == '0':
            order.dinner = False
        else:
            order.dinner = True
        dessert = form.cleaned_data.get("dessert")
        if dessert == '0':
            order.dessert = False
        else:
            order.dessert = True
        order.amount_person = form.cleaned_data.get("amount_person")
        order.result = int(order.time) * int(order.amount_person) * (
                int(order.breakfast) * 50 +
                int(order.lunch) * 50 +
                int(order.dinner) * 50 +
                int(order.dessert) * 50
        )
        milk_allergy = form.cleaned_data.get("milk_allergy")
        nuts_allergy = form.cleaned_data.get("nuts_allergy")
        honey_allergy = form.cleaned_data.get("honey_allergy")
        cereal_allergy = form.cleaned_data.get("cereal_allergy")
        meat_allergy = form.cleaned_data.get("meat_allergy")
        fish_allergy = form.cleaned_data.get("fish_allergy")
        milk_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Молочные продукты")
        nuts_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Орехи и бобовые")
        honey_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Продукты пчеловодства")
        cereal_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Зерновые")
        meat_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Мясо")
        fish_allergy_obj, created = AllergyCategory.objects.get_or_create(
            title=
            "Рыба и морепродукты")
        if milk_allergy:
            order.allergies.add(milk_allergy_obj)
        else:
            if milk_allergy_obj in order.allergies.all():
                order.allergies.remove(milk_allergy_obj)
        if nuts_allergy:
            order.allergies.add(nuts_allergy_obj)
        else:
            if nuts_allergy_obj in order.allergies.all():
                order.allergies.remove(nuts_allergy_obj)
        if honey_allergy:
            order.allergies.add(honey_allergy_obj)
        else:
            if honey_allergy_obj in order.allergies.all():
                order.allergies.remove(honey_allergy_obj)
        if cereal_allergy:
            order.allergies.add(cereal_allergy_obj)
        else:
            if cereal_allergy_obj in order.allergies.all():
                order.allergies.remove(cereal_allergy_obj)
        if meat_allergy:
            order.allergies.add(meat_allergy_obj)
        else:
            if meat_allergy_obj in order.allergies.all():
                order.allergies.remove(meat_allergy_obj)
        if fish_allergy:
            order.allergies.add(fish_allergy_obj)
        else:
            if fish_allergy_obj in order.allergies.all():
                order.allergies.remove(fish_allergy_obj)
        order.save()
    if promo_form.is_valid():
        try:
            user_promocode = promo_form.cleaned_data.get("promocode")
            try:
                promocode = Promocode.objects.get(promocode=user_promocode)
                discount = promocode.discount / 100
                order.result = order.result - order.result * discount

                correct_promocode = True
            except Promocode.DoesNotExist:
                pass
        except AttributeError:
            pass

    order.result += order.food_form_cost
    order.save()

    context = {'form': form,
               'promo_form': promo_form,
               'food_form': food_form,
               'result': order.result,
               'time': order.time,
               'breakfast': order.breakfast,
               'lunch': order.lunch,
               'dinner': order.dinner,
               'dessert': order.dessert,
               'amount_person': order.amount_person,
               'promocode': user_promocode,
               'correct_promocode': correct_promocode,
               'food_form_cost': order.food_form_cost,

templates/card1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <a class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green" href="{% url 'profile' %}">Назад</a>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="img/circle1.png" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
                        <h2>Название рецепта</h2>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                            <li class="list-group-item">ингредиент (500г.)</li>
                        </ul>
                        <h6>Общая калорийность: 1000 ккал</h6>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="https://vk.com/devmanorg">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="{% url 'home' %}" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

templates/lk.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <a class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green" href="{% url 'account_logout' %}">Выйти</a>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>     
            <div class="container">
                <div class="row">
                    <div class="card col-12 p-3 mb-5 foodplan__shadow">
                        <h4 class="foodplan__backButton">
                            <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
                        </h4>
                        <h2 class="text-center"><strong>Личный кабинет</strong></h2>
                        {% if messages %}
                        {% for message in messages %}
                        <div id="message">
                        <div id="inner-message" class="alert alert-warning alert-dismissible fade show" role="alert">
                            {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
                        <div class="position-relative">
                            <img src="{{ profile.avatar.url }}" alt="" width="100" height="100" class="rounded-pill">
                            <label for="id_avatar">
                            <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus">+
                                
                            </span>
                            </label>
                        </div>
                        <h3 class="card-title text-center">{{ profile.user }}</h3>
                        <div class="d-block">
                            <a class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green" href="{% url 'account_logout' %}">Выйти</a>
                        </div>
                    </div>

                    <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
                            <ul class="nav nav-tabs">
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab2" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                                </li>                                
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab1" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                                </li>
                                <li class="nav-item foodplan__tab-item flex-grow-1"></li>
                            </ul>
                            <div class="tab-content mt-2">

                                <div class="tab-pane fade" id="data">
                                    <form method="post" action="{% url 'profile' %}" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="id_name" class="form-label">Имя</label>
                                                <small><a href="#" name="trigger" class="link-dark foodplan_green">изменить</a></small>
                                            </div>
                                        
                                            <input type="text" class="form-control" name="name" value="{{ profile.user }}" required id="id_name">
                                        </div>
                                        <div class="mb-3">
                                            <label for="id_email" class="form-label">Email</label>
                                            <input type="email" class="form-control" name="email" value="{{ profile.user.email }}" required id="id_email" aria-describedby="emailHelp">
                                        </div>
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="exampleInputPassword1" class="form-label">Пароль</label>
                                                <small><a href="#" class="link-dark foodplan_green">изменить</a></small>
                                            </div>
                                        
                                            <input type="password" class="form-control" name="password" id="password">
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputPassword1" class="form-label">Подтверждение пароля</label>
                                            <input type="password" class="form-control" name="password_confirm" id="PasswordConfirm">
                                        </div>
                                        <input type="file" class="form-control" name="avatar" accept=".jpg, .jpeg, .png" id="id_avatar" hidden>
                                        <div class="d-block">
                                            <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green" disabled>Сохранить
                                                изменения</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="tab-pane fade show active" id="menu">
                                    <div class="row">
                                        {% if order %}
                                        <div class="col-2">
                                            <img src="{% static 'circle1.png' %}" alt="" class="w-100">
                                        </div>
                                        <div class="col-10 col-md-10">
                                            <div class="row">
                                                <div class="col-12">
                                                    <h2>{{ order.description }}</h2>
                                                </div>
                                                <div class="col-md-12 col-lg-9">
                                                    <h6>Ваше меню на {{ order.date }}:</h6>
                                                    {% if order.breakfast %}
                                                    Завтрак: <a href="{% url 'recipes:recipe_page' order.breakfast.id %}">{{ order.breakfast.title }}</a>
                                                    <br>
                                                    {% endif %}
                                                    {% if order.lunch %}
                                                    Обед: <a href="{% url 'recipes:recipe_page' order.lunch.id %}">{{ order.lunch.title }}</a>
                                                    <br>
                                                    {% endif %}
                                                    {% if order.dinner %}
                                                    Ужин: <a href="{% url 'recipes:recipe_page' order.dinner.id %}">{{ order.dinner.title }}</a>
                                                    <br>
                                                    {% endif %}
                                                    {% if order.dessert %}
                                                    Десерт: <a href="{% url 'recipes:recipe_page' order.dessert.id %}">{{ order.dessert.title }}</a>
                                                    <br>
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 col-lg-3 text-muted d-flex flex-column justify-content-between">
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Персоны: </small><small>{{ order.amount_person }}</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Аллергии: </small>
                                                    </div>
                                                    <ul>{% for allergy in order.allergies %}
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <li style="font-size:13px;">{{ allergy }}</li>
                                                    </div>
                                                    {% endfor %}
                                                    </ul>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Калории: </small><small>{{ order.calories }}</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Кол-во приёмов пищи: </small><small>{{ order.amount_meals }}</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% else %}
                                            <h6>У вас нет активной подписки</h6>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>                
                    </div>
                </div>
            </div>

        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="https://vk.com/devmanorg">
                        <img src="{% static 'vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6><a href="#"
                    class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
        
     $(document).ready(function(){

         $("input[name=name],input[name=email]").prop("disabled",true);

         $("a[name=trigger]").on("click",function(){

                 $("input[name=name],input[name=email],select").removeAttr("disabled");
                 $("button[type=submit],select").prop("disabled",false);
         })

         $("input[name=save]").on("click",function(){

             $("input[name=name],input[name=email],select").prop("disabled",true);
         })
     })
    </script>   
</body>